version: '3.8'

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - /Users/amsaoub/Desktop/inception_git/srcs/requirements:/var/www/wordpress
    depends_on:
      - wordpress
    restart: on-failure

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: on-failure

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - /Users/amsaoub/Desktop/inception_git/srcs/requirements:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure
